services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: netflix_flask
    depends_on:
      - mariadb
    ports:
      - 81:80
    volumes:
      - .:/app

  mariadb:
    image: mariadb:10.6.20
    container_name: netflix_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: netflix
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3307:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: netflix_phpmyadmin
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8081:80
volumes:
  mariadb_data:
